### PR TITLE
Code for login page.

### PR DESCRIPTION
**Pull request by GcvKishore**
Please check all the changes done on the new page.

### CODE REVIEW

**Review by Amulya301 — CHANGES_REQUESTED** [review]
Reviewed the files. Just need to close the button tag in line13 of  index.html file.

**Review by Vedvund — APPROVED** [review]
satisfactory

**Review by priyushasunkara — APPROVED** [review]
looks good

**Review by Amulya301 — APPROVED** [review]
looks good and structured.

**Pull request merged**
