### PR TITLE
Week 2

### PR DESCRIPTION
**Pull request by Vedvund**
Week 2 - Web Pages (HTML/CSS/BOOTSTRAP) - Final Version

### CODE REVIEW

**Review by Vedvund — COMMENTED** [review]
Suggestion: We might need to think about the file names

**Comment by GcvKishore** [comment]
My idea about the file names is to simply represent them with their particular types, as we are displaying different pages with different types. So for instance, can page 2_4 be replaced as a file upload? @Vedvund @Amulya301 @priyushasunkara

**Comment by Amulya301** [comment]
Yeah we can represent in this way also, as chaitanya said. Since, it would be readable by others.

**Review by GcvKishore — APPROVED** [review]
No bugs found as much as I can see it according to our requirements. Hence, would like to merge the branch.
Thank You!

**Pull request merged**
