### PR TITLE
Support team contact form

### LINKED ISSUE #78: Tutest support team contact form
Users need to have a contact form where the user can reach out to the support team

### PR DESCRIPTION
**Pull request by Vedvund**
Now users can send support team messages in order to inform any issue

### CODE REVIEW

**Review by priyushasunkara — APPROVED** [review]
Everything looks  good
No bugs found

**Review by Amulya301 — APPROVED** [review]
Working as expected.

**Review by GcvKishore — COMMENTED** [review]
Working expectedly.

**Review by GcvKishore — APPROVED** [review]
Working expectedly

**Pull request merged**
